## 인덱싱, 슬라이싱 기본

In [19]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr[5]

5

In [21]:
arr[5:8]

array([5, 6, 7])

In [22]:
arr[5:8] = 10
arr

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

- 파이썬 리스트와 크게 다른점중의 하나는 배열 슬라이스는 새로운 객체를 만드는 것이 아닌 원래 배열에 대한 뷰(view)이다.  
- 즉 선택 부분의 값을 변경하면 원래 배열의 같은 위치의 값도 변경이 되는 것이다.

In [23]:
arr_slice = arr[5:8]
arr_slice

array([10, 10, 10])

In [24]:
arr_slice[1] = 1234
arr

array([   0,    1,    2,    3,    4,   10, 1234,   10,    8,    9])

- 시작과 끝이 없는 슬라이싱은 모든 원소 선택

In [25]:
arr_slice[:] = 500
arr

array([  0,   1,   2,   3,   4, 500, 500, 500,   8,   9])

- 배열의 일부분을 복사해서 사용하려면 copy 메소드 이용

In [26]:
arr_copy = arr[5:8].copy()
arr_copy

array([500, 500, 500])

In [29]:
arr_copy[:] = -100
arr_copy

array([-100, -100, -100])

In [30]:
arr
#변경되지 않음

array([  0,   1,   2,   3,   4, 500, 500, 500,   8,   9])

- 고차원 배열

In [31]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[0]

array([1, 2, 3])

In [32]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [34]:
arr2d[1,1:]

array([5, 6])

In [35]:
arr2d[:2,2]

array([3, 6])

In [36]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [37]:
arr2d[:2,1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### 논리 인덱싱

In [38]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

np.random.seed(0)

data = np.random.randn(7, 4)
data

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385]])

In [39]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [40]:
data[names == "Bob"]

array([[1.76405235, 0.40015721, 0.97873798, 2.2408932 ],
       [0.76103773, 0.12167502, 0.44386323, 0.33367433]])

In [41]:
data[names == 'Bob', 2:]

array([[0.97873798, 2.2408932 ],
       [0.44386323, 0.33367433]])

In [42]:
data[names != 'Bob']

array([[ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385]])

In [43]:
data[~(names == 'Bob')]

array([[ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385]])

- 여러 개의 조건을 결합하려면 &(and) 또는 |(or) 연산자를 사용하면 된다. 
- 주의해야 할 것은 넘파이 논리 연산자로 파이썬 논리 연산자 and와 or를 사용할 수 없다. 반드시 &와 |만 사용해야 한다.

In [44]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [45]:
arr_m = data[mask]
arr_m

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574]])

- 또한 논리 인덱스를 이용해서 반환된 배열을 **원래 배열의 복사본**이기때문에 반환된 배열값이 바뀌어도 원본값은 변하지 않는다.

In [46]:
arr_m[:, :2] = 0
arr_m

array([[ 0.        ,  0.        ,  0.97873798,  2.2408932 ],
       [ 0.        ,  0.        ,  0.14404357,  1.45427351],
       [ 0.        ,  0.        ,  0.44386323,  0.33367433],
       [ 0.        ,  0.        ,  0.3130677 , -0.85409574]])

In [47]:
data

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385]])

In [48]:
data[data < 0] = 0
data

array([[1.76405235, 0.40015721, 0.97873798, 2.2408932 ],
       [1.86755799, 0.        , 0.95008842, 0.        ],
       [0.        , 0.4105985 , 0.14404357, 1.45427351],
       [0.76103773, 0.12167502, 0.44386323, 0.33367433],
       [1.49407907, 0.        , 0.3130677 , 0.        ],
       [0.        , 0.6536186 , 0.8644362 , 0.        ],
       [2.26975462, 0.        , 0.04575852, 0.        ]])

In [49]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.86755799, 0.        , 0.95008842, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.6536186 , 0.8644362 , 0.        ],
       [2.26975462, 0.        , 0.04575852, 0.        ]])

### 정수 배열을 이용한 인덱싱

In [4]:
import numpy as np
arr = np.empty((8,4))

for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [5]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [7]:
arr[[-4,-3,0,6]]

array([[4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

#### np.range와 np.arange 의 차이
1. range 함수에는 정수 단위만 지원하나, np.arange는 실수 단위도 표현 가능하다.
2. range 메소드는 range iterator 자료형을 반환하고, np.arange 메소드는 numpy array 자료형을 반환. 따라서, np.arange 메소드 결과는 넘파이에서 수행하는 연산 연계가 가능
3. for 문 등에서 순회하고 싶은 수열이 정수로 구성되어 있다면, range 메소드로 순회하는 것이 수행시간에 있어 조금 더 유리

In [8]:
arr = np.range(32).reshape(8,4) ## range는 넘파이 연산 연계 불가능
arr

AttributeError: module 'numpy' has no attribute 'range'

In [9]:
arr = np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [10]:
arr[[1,5,7,2], [0,3,1,2]]

array([ 4, 23, 29, 10])

In [11]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### 배열 전치 및 축 교환

In [13]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [16]:
arr.dot(arr.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [17]:
arr3d = np.arange(2*3*4).reshape((2,3,4))
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [18]:
arr3d.T

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

## 범용함수

In [19]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [21]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [22]:
np.add(arr,arr)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
rng = np.random.RandomState(0)

x = rng.randn(10)
y = rng.randn(10)
x

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [24]:
y

array([ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
        0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574])

In [25]:
np.maximum(x,y)

array([ 1.76405235,  1.45427351,  0.97873798,  2.2408932 ,  1.86755799,
        0.33367433,  1.49407907, -0.15135721,  0.3130677 ,  0.4105985 ])

In [26]:
arr = rng.randn(7) * 5
arr

array([-12.76494908,   3.26809298,   4.32218099,  -3.7108251 ,
        11.34877312,  -7.27182837,   0.22879259])

-  modf라는 함수는 정수와 소수부분을 각각 반환한다.

In [27]:
rem_part, int_part = np.modf(arr)
rem_part

array([-0.76494908,  0.26809298,  0.32218099, -0.7108251 ,  0.34877312,
       -0.27182837,  0.22879259])

In [28]:
int_part

array([-12.,   3.,   4.,  -3.,  11.,  -7.,   0.])

In [29]:
np.sqrt(arr, out=arr)


<ipython-input-29-ab2a05aff831>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, out=arr)


array([       nan, 1.80778676, 2.07898557,        nan, 3.36879402,
              nan, 0.47832268])

In [31]:
arr

array([       nan, 1.80778676, 2.07898557,        nan, 3.36879402,
              nan, 0.47832268])